# @package habitat_baselines.rl.policy.hierarchical_policy.defined_skills
# See `oracle_skills.yaml` for details.

wait:
  skill_name: "WaitSkillPolicy"
  action_name: "wait"
  obs_skill_inputs: []
  max_skill_steps: -1
  ignore_grip: True

nav_to_obj:
  skill_name: "NoopSkillPolicy"
  obs_skill_inputs: ["goal_to_agent_gps_compass"]
  max_skill_steps: 1
  apply_postconds: False
  force_end_on_timeout: False
  obs_skill_input_dim: 2
  pddl_action_names: ["nav_to_obj", "nav_to_goal", "nav_to_receptacle_by_name"]
  ignore_grip: True
