
---
dataset_path: "data/replica_cad/replicaCAD.scene_dataset_config.json"
additional_object_paths:
  - "data/objects/ycb/configs/"
scene_sets:
  -
    name: "scene_train_split"
    included_substrings:
      - "v3_sc0_staging"
      - "v3_sc1_staging"
      - "v3_sc2_staging"
    excluded_substrings: []
  -
    name: "scene_val_split"
    included_substrings:
      - "v3_sc3_staging"
    excluded_substrings: []
  -
    name: "scene_test_split"
    included_substrings:
      - "v3_sc4_staging"
    excluded_substrings: []

object_sets:
  -
    name: "kitchen"
    included_substrings:
    - "003_cracker_box"
    - "013_apple"
    - "005_tomato_soup_can"
    - "072-b_toy_airplane"
    - "053_mini_soccer_ball"
    - "030_fork"
    - "061_foam_brick"
    - "019_pitcher_base"
    - "065-c_cups"
    - "065-e_cups"
    - "021_bleach_cleanser"
    - "004_sugar_box"
    - "065-b_cups"
    - "028_skillet_lid"
    - "008_pudding_box"
    - "011_banana"
    - "033_spatula"
    - "073-a_lego_duplo"
    - "072-a_toy_airplane"
    - "063-b_marbles"
    - "026_sponge"
    - "014_lemon"
    - "065-a_cups"
    - "065-f_cups"
    - "054_softball"
    - "027_skillet"
    - "065-j_cups"
    - "073-b_lego_duplo"
    - "016_pear"
    - "073-c_lego_duplo"
    - "051_large_clamp"
    - "058_golf_ball"
    - "002_master_chef_can"
    - "036_wood_block"
    - "055_baseball"
    - "057_racquetball"
    - "037_scissors"
    - "072-e_toy_airplane"
    - "017_orange"
    - "070-b_colored_wood_blocks"
    - "042_adjustable_wrench"
    - "065-h_cups"
    - "073-d_lego_duplo"
    - "029_plate"
    - "072-c_toy_airplane"
    - "071_nine_hole_peg_test"
    - "007_tuna_fish_can"
    - "065-g_cups"
    - "065-d_cups"
    - "077_rubiks_cube"
    - "063-a_marbles"
    - "043_phillips_screwdriver"
    - "025_mug"
    - "070-a_colored_wood_blocks"
    - "052_extra_large_clamp"
    - "056_tennis_ball"
    - "065-i_cups"
    - "072-d_toy_airplane"
    - "050_medium_clamp"
    - "038_padlock"
    - "012_strawberry"
    - "032_knife"
    - "040_large_marker"
    - "059_chain"
    - "031_spoon"
    - "022_windex_bottle"
    - "073-e_lego_duplo"
    - "073-f_lego_duplo"
    - "024_bowl"
    - "018_plum"
    - "010_potted_meat_can"
    - "048_hammer"
    - "062_dice"
    - "015_peach"
    - "073-g_lego_duplo"
    - "035_power_drill"
    - "044_flat_screwdriver"
    - "009_gelatin_box"
    - "006_mustard_bottle"

    excluded_substrings: []
    comment: "Leave included_substrings empty to select all objects."

receptacle_sets:
  -
    name: "table"
    included_object_substrings:
      - "frl_apartment_picture_04"
      - "frl_apartment_kitchen_utensil_06"
      - "frl_apartment_cushion_03"
      - "frl_apartment_kitchen_utensil_03"
      - "frl_apartment_table_01"
      - "frl_apartment_monitor"
      - "frl_apartment_cushion_01"
      - "frl_apartment_bowl_03"
      - "frl_apartment_towel"
      - "frl_apartment_plate_01"
      - "frl_apartment_shoe_04"
      - "frl_apartment_wall_cabinet_03"
      - "frl_apartment_refrigerator"
      - "frl_apartment_table_04"
      - "frl_apartment_bin_02"
      - "frl_apartment_vase_01"
      - "frl_apartment_kitchen_utensil_01"
      - "frl_apartment_cup_05"
      - "frl_apartment_lamp_01"
      - "frl_apartment_kitchen_utensil_04"
      - "frl_apartment_kitchen_utensil_05"
      - "frl_apartment_basket"
      - "frl_apartment_handbag"
      - "frl_apartment_rack_01"
      - "frl_apartment_book_06"
      - "frl_apartment_box"
      - "frl_apartment_plate_02"
      - "frl_apartment_rug_01"
      - "frl_apartment_shoe_03"
      - "frl_apartment_book_02"
      - "frl_apartment_chair_04"
      - "frl_apartment_book_03"
      - "frl_apartment_cup_02"
      - "frl_apartment_indoor_plant_01"
      - "frl_apartment_clothes_hanger_01"
      - "frl_apartment_setupbox"
      - "frl_apartment_kitchen_utensil_02"
      - "frl_apartment_vase_02"
      - "frl_apartment_kitchen_utensil_09"
      - "frl_apartment_camera_02"
      - "frl_apartment_cloth_03"
      - "frl_apartment_indoor_plant_02"
      - "frl_apartment_cloth_04"
      - "frl_apartment_bowl_06"
      - "frl_apartment_book_04"
      - "frl_apartment_tvstand"
      - "frl_apartment_cloth_01"
      - "frl_apartment_cabinet"
      - "frl_apartment_remote-control_01"
      - "frl_apartment_wall_cabinet_02"
      - "frl_apartment_umbrella"
      - "frl_apartment_chair_01"
      - "frl_apartment_monitor_stand"
      - "frl_apartment_shoebox_01"
      - "frl_apartment_bin_03"
      - "frl_apartment_choppingboard_02"
      - "frl_apartment_shoe_01"
      - "frl_apartment_table_03"
      - "frl_apartment_cup_01"
      - "frl_apartment_knifeblock"
      - "frl_apartment_sponge_dish"
      - "frl_apartment_clothes_hanger_02"
      - "frl_apartment_bike_01"
      - "frl_apartment_cloth_02"
      - "frl_apartment_pan_01"
      - "frl_apartment_picture_02"
      - "frl_apartment_tv_screen"
      - "frl_apartment_lamp_02"
      - "frl_apartment_book_01"
      - "frl_apartment_table_02"
      - "frl_apartment_tv_object"
      - "frl_apartment_bike_02"
      - "frl_apartment_picture_03"
      - "frl_apartment_stool_02"
      - "frl_apartment_clock"
      - "frl_apartment_small_appliance_02"
      - "frl_apartment_kitchen_utensil_08"
      - "frl_apartment_sofa"
      - "frl_apartment_rug_02"
      - "frl_apartment_bowl_02"
      - "frl_apartment_cup_03"
      - "frl_apartment_wall_cabinet_01"
      - "frl_apartment_chair_05"
      - "frl_apartment_shoe_02"
      - "frl_apartment_picture_01"
      - "frl_apartment_bin_01"
      - "frl_apartment_bowl_01"
      - "frl_apartment_book_05"
      - "frl_apartment_mat"
      - "frl_apartment_small_appliance_01"
      - "frl_apartment_bowl_07"
      - "frl_apartment_beanbag"
    excluded_object_substrings: []
    included_receptacle_substrings:
      - ""
    excluded_receptacle_substrings: []
    comment: "The empty substrings act like wildcards, selecting all receptacles for all objects."

  -
    name: "inside_fridge"
    included_object_substrings:
      - ""
    excluded_object_substrings: []
    included_receptacle_substrings:
      - "receptacle_aabb_middle_topfrl_apartment_refrigerator"
    excluded_receptacle_substrings: []

  -
    name: "inside_drawer"
    included_object_substrings:
      - ""
    excluded_object_substrings: []
    included_receptacle_substrings:
      - receptacle_aabb_drawer_left_bottom_frl_apartment_kitchen_counter
      - receptacle_aabb_drawer_left_top_frl_apartment_kitchen_counter
      - receptacle_aabb_drawer_middle_bottom_frl_apartment_kitchen_counter
      - receptacle_aabb_drawer_middle_middle_frl_apartment_kitchen_counter
      - receptacle_aabb_drawer_middle_top_frl_apartment_kitchen_counter
      - receptacle_aabb_drawer_right_bottom_frl_apartment_kitchen_counter
      - receptacle_aabb_drawer_right_top_frl_apartment_kitchen_counter
    excluded_receptacle_substrings: []

scene_sampler:
  type: "subset"
  params:
    scene_sets: ["scene_train_split", "scene_val_split"]


object_samplers:
  -
    name: "kitchen_counter"
    type: "uniform"
    params:
      object_sets: ["kitchen"]
      receptacle_sets: ["table", "inside_fridge", "inside_drawer"]
      num_samples: [5, 5]
      orientation_sampling: "up"

object_target_samplers:
  -
    name: "any_targets"
    type: "uniform"
    params:
      object_samplers: ["kitchen_counter"]
      receptacle_sets: ["table", "inside_fridge", "inside_drawer"]
      num_samples: [5, 5]
      orientation_sampling: "up"


markers:
  - name: "cab_push_point_7"
    type: "articulated_object"
    params:
      offset: [0.3,0.0,0]
      link: "drawer1_top"
      object: "kitchen_counter_:0000"
  - name: "cab_push_point_6"
    type: "articulated_object"
    params:
      offset: [0.3,0.0,0]
      link: "drawer2_top"
      object: "kitchen_counter_:0000"
  - name: "cab_push_point_5"
    type: "articulated_object"
    params:
      offset: [0.3,0.0,0]
      link: "drawer3"
      object: "kitchen_counter_:0000"
  - name: "cab_push_point_4"
    type: "articulated_object"
    params:
      offset: [0.3,0.0,0]
      link: "drawer4"
      object: "kitchen_counter_:0000"
  - name: "fridge_push_point"
    type: "articulated_object"
    params:
      offset: [0.10,-0.62,0.2]
      link: "top_door"
      object: "fridge_:0000"
