# The rearrangement task with robot_1 perceives the target object first.
# Make sure the robot_0 is spot and the robot_1 is drone.
objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  - name: TARGET_any_targets|0
    expr_type: goal_entity_type
  - name: robot_0
    expr_type: robot_entity_type
  - name: robot_1
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    # - at(any_targets|0,TARGET_any_targets|0)
    - robot_at(TARGET_any_targets|0, robot_0)
    


stage_goals:
  stage_1:
    expr_type: AND
    sub_exprs:
      - robot_at(any_targets|0, robot_0)
  stage_2:
    expr_type: AND
    sub_exprs:
      - robot_at(TARGET_any_targets|0, robot_0)

solution:
  - nav_to_goal(any_targets|0, robot_0)
  # - pick(any_targets|0, robot_0)
  - nav_to_obj(TARGET_any_targets|0, robot_0)
  # - place(any_targets|0,TARGET_any_targets|0, robot_0)
