objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  - name: any_targets|1
    expr_type: movable_entity_type
  - name: any_targets|2
    expr_type: movable_entity_type
  - name: any_targets|3
    expr_type: movable_entity_type
  - name: robot_0
    expr_type: robot_entity_type
  - name: robot_1
    expr_type: robot_entity_type
  - name: robot_2
    expr_type: robot_entity_type
  - name: robot_3
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    - robot_at(any_targets|0, robot_0)
    - robot_at(any_targets|1, robot_1)
    - robot_at(any_targets|2, robot_2)
    - robot_at(any_targets|3, robot_3)
    - detected_object(any_targets|0, robot_0)
    - detected_object(any_targets|1, robot_1)
    - detected_object(any_targets|2, robot_2)
    - detected_object(any_targets|3, robot_3)

stage_goals:
  stage_1:
    expr_type: AND
    sub_exprs:
      - robot_at(any_targets|0, robot_0)
      - robot_at(any_targets|1, robot_1)
      - robot_at(any_targets|2, robot_2)
      - robot_at(any_targets|3, robot_3)
  stage_2:
    expr_type: AND
    sub_exprs:
      - detected_object(any_targets|0, robot_0)
      - detected_object(any_targets|1, robot_1)
      - detected_object(any_targets|2, robot_2)
      - detected_object(any_targets|3, robot_3)

solution:
  - nav_to_goal(any_targets|0, robot_0)
  - nav_to_goal(any_targets|1, robot_1)
  - nav_to_goal(any_targets|2, robot_2)
  - nav_to_goal(any_targets|3, robot_3)
